[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.tokenizer", "php82Extensions.bcmath", "php82Extensions.ctype", "php82Extensions.fileinfo", "php82Extensions.curl", "php82Extensions.dom", "php82Extensions.session", "php82Extensions.fpm", "nginx", "composer"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --class=CategorySeeder --force && php-fpm82 -D && sed 's/$PORT/'$PORT'/g' nginx.conf > /tmp/nginx.conf && nginx -c /tmp/nginx.conf -g 'daemon off;'"